from datamorph.statistical_learning.gaussian_processes import GaussianProcessesEngine
from datamorph.statistical_learning.hidden_markov_models import HiddenMarkovModelsEngine
from datamorph.statistical_learning.kernel_ridge_regression import KernelRidgeRegressionEngine
from datamorph.statistical_learning.quantile_regression import QuantileRegressionEngine
from datamorph.statistical_learning.robust_statistics import RobustStatisticsEngine
from datamorph.statistical_learning.discriminant_analysis import DiscriminantAnalysisEngine
from datamorph.statistical_learning.isotonic_regression import IsotonicRegressionEngine
from datamorph.statistical_learning.generalized_additive_models import GeneralizedAdditiveModelsEngine
